### ISSUE TITLE
How well does your model perform?

### ISSUE THREAD

**Issue by rickyhan** [happynoom/DeepTrade#2]
I am working on a similar project with a slightly different architecture. It is trained on cryptocurrency data because it's a lot more granular(1m candles). It consistently beats the market by a small margin of 3-10% compared to random and 1-18% to buy and hold.

One of the major signals I am using is ADX.

I am sharing the private repo with you. Please check your invite

**Comment by happynoom** [comment]
@rickyhan Thank you, I will try ADX. I haven't seen your invite.  You sent on email or QQ?

**Comment by rickyhan** [comment]
Just emailed you
