### ISSUE TITLE
can't find relu

### ISSUE THREAD

**Issue by naturelan00** [happynoom/DeepTrade#3]
hello, I run DeepTrader.py, but there is a error as following pic. I want to ask the relu function is missing or I need to define it myself ?
![image](https://user-images.githubusercontent.com/26559064/31316278-fb9c0af6-abef-11e7-89eb-7711154ad1ef.png)
Thanks!

**Comment by happynoom** [comment]
确认一下tensorflow的版本，我用的1.0以上版本

**Comment by happynoom** [comment]
抱歉，DeepTrader.py已经删除，运行smarttrader.py
