### ISSUE TITLE
'amount' mystery field

### ISSUE THREAD

**Issue by jmatzen** [happynoom/DeepTrade#4]
Hello.  This is a very nice starting point.  What is the last column named `amount` in the dataset?

**Comment by happynoom** [comment]
It means the amount of stock units that have been sell or bought during that day.

**Comment by jmatzen** [comment]
How's that different than volume then?  I finally noticed that the field doesn't seem to be used by your model though, so it's still a bit confusing.  Thanks for replying.

**Comment by happynoom** [comment]
Yes,it’s not used in the model, it’s just a basic data of trade
