### ISSUE TITLE
这个损失函数， 当p为0时，loss永远就等于0

### ISSUE THREAD

**Issue by TIANRENK** [happynoom/DeepTrade#6]
也就是说，用这个loss训练模型，模型只要输出的p为0就可以是损失最小。

**Comment by happynoom** [comment]
> 也就是说，用这个loss训练模型，模型只要输出的p为0就可以是损失最小。

注意损失函数可以为负，为负就是指盈利，p=0时含义是不交易，不交易没有损失很正常。

**Comment by happynoom** [comment]
不交易无损失
